### PR TITLE
Fix vars.rst file

### PR DESCRIPTION
**Pull request by robflop**
Adjusted the entry of the official docs to be proper.

### CODE REVIEW

**Comment by robflop** [comment]
@macdja38 Could I get some feedback on this?

**Comment by macdja38** [comment]
Umm... wouldn't you also have to update everything that links to this?

**Comment by robflop** [comment]
GitHub is doing some weird ass shit here, with me having to resolve conflicts twice like that.
I don't know why, but it's the only way it works.

**Comment by macdja38** [comment]
This message is confusing and misleading written like this though, this is the up to date official documentation for discordv8, you're linking to discord.js

**Comment by robflop** [comment]
I guess that's accurate. I made the PR when this change had not yet occurred.

**Pull request closed without merging**
