### PR TITLE
docs fix

### PR DESCRIPTION
**Pull request by Drahcirius**
image

It's been over a year since 8.2 and this is still happening. When people google how to log in using discord.js they still get these docs. Do you think they'll click the examples directly or go to the main site? I think the answer is obvious.
image

It's absurd that it's been over a year and people still get the wrong docs. Either take it down or 301 redirect them to the correct documentation.

### CODE REVIEW

**Comment by macdja38** [comment]
It's very clearly labeled 8.2, their are warnings in the docs that say it's the older version. If you would like to create a pr that ads a "this is the old warning" header to each page that could be helpfull?

**Comment by Drahcirius** [comment]
You know what you can do?
Host these docs locally in your computer.
Then go to your hosts file and add in an entry
`127.0.0.1 discordjs.readthedocs.io`
And you'll be the only one who ever sees the docs, instead of misleading hundreds of people.

**Comment by macdja38** [comment]
idk if readthedocs supports that. And that would stop the people that want to read them from finding them.

**Comment by Drahcirius** [comment]
macdja, real talk: nobody uses the v8 docs except for you
The purpose of the host file is so that the link would be valid only for your computer.
That way you can take it down and do a solid for the entire discord community, and keep it up for yourself.

**Comment by Drahcirius** [comment]
image

Oh look, another person today who went to the wrong docs @macdja38

**Comment by Drahcirius** [comment]
This too, from last week 
image

**Comment by Drahcirius** [comment]
How about this one
image

**Comment by Drahcirius** [comment]
People are unintentionally misleading people in djs support channels too
image

**Comment by Drahcirius** [comment]
Whoops, wrong constants
image

**Comment by Drahcirius** [comment]
Ah, let me find....the wrong docs
image

**Comment by Drahcirius** [comment]
I wonder why this event doesn't do anything
image

**Comment by Drahcirius** [comment]
Its in the docs though
image

**Comment by Drahcirius** [comment]
Oops, he doesn't know which docs to look at
image

**Comment by Drahcirius** [comment]
It's here bruh
image

**Comment by Drahcirius** [comment]
Using the old docs?
image

**Comment by Drahcirius** [comment]
I wonder why that doesn't work?...
image

**Comment by Drahcirius** [comment]
Oh, if only they found the right docs...
image

**Comment by Drahcirius** [comment]
Probably because muteMember isn't in the latest version
image

**Comment by Drahcirius** [comment]
Nope, those those
image

**Comment by Drahcirius** [comment]
Maybe we should add some of these back...nah, why would we add shit code?
image

**Comment by Drahcirius** [comment]
Hmm....I wonder why this basic example doesn't work
image

**Comment by Drahcirius** [comment]
Unfortunate.
image

**Comment by Drahcirius** [comment]
Yeah, according to THE OLD DOCS
image

**Comment by Drahcirius** [comment]
image

**Comment by Drahcirius** [comment]
hey @macdja38 thanks for reading through this month's Wrong Docs magazine.
I hope you're ready because there's no unsubscribing.
EDIT: I take that back, you can unsubscribe by taking down the docs

**Comment by appellation** [comment]
Discord.js v8.x is not supported by the developers of the Discord.js library.  Therefore, if you wish to maintain documentation for an unsupported fork of the Discord.js library, you have two options:

1. maintain that documentation privately, where it is not accessible online or through search engines
2. rename your unsupported fork of the Discord.js library to delineate it as the *completely separate library* that it is

Let me reiterate that maintained versions of Discord.js v8.x are completely separate from Discord.js itself.  By keeping this documentation online, you are deliberately misappropriating the Discord.js name and misleading Discord.js users.

**Pull request closed without merging**
